MyPackage/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>gameResult Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyPackage/main/default/objects/Game__c/fields/Game_Over__c.field-meta.xml
<CustomField>
    <fullName>Game_Over__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Game Over</label>
    <type>Checkbox</type>
</CustomField>

MyPackage/main/default/objects/Game__c/fields/Move_Trace__c.field-meta.xml
<CustomField>
    <fullName>Move_Trace__c</fullName>
    <label>Move Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

MyPackage/main/default/classes/SimonApexController.cls
public with sharing class SimonApexController {
    @AuraEnabled
    public static Game__c createNewGame(){
        Game__c newGame = new Game__c();
        insert newGame;
        return newGame;
    }
    @AuraEnabled
    public static Game__c updateGameTrace(String gameId, String trace, Integer record) {
        Game__c myGame = [SELECT Id FROM Game__c WHERE Id = :gameId LIMIT 1];
        myGame.Move_Trace__c = trace;
        myGame.Game_Over__c = true;
        myGame.Record__c = record;
        update myGame;
        return myGame;
    }
}